version: "3.7"

services:

  edge:
    image: xumj1975/svnedge:6.0.2-9
    ports:
      - "18080:18080"
      - "3343:3343"
    environment:
      SET_PERMS: "false"
    volumes:
      - ./data:/home/svnedge/csvn/data
